
SET IDENTITY_INSERT Materia ON 
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (1, 'Ajedréz', 10,'Ajedréz', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (2, 'Economía', 16,'Ciencias Económicas', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (3, 'Biología', 18,'Ciencias Naturales y Educación Ambiental', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (4, 'Ciencias', 18,'Ciencias Naturales y Educación Ambiental', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (5, 'Física', 18,'Ciencias Naturales y Educación Ambiental', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (6, 'Química', 18,'Ciencias Naturales y Educación Ambiental', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (7, 'Democracia', 14,'Ciencias Sociales', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (8, 'Geografía', 16,'Ciencias Sociales', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (9, 'Historia', 14,'Ciencias Sociales', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (10, 'Sociales', 14,'Ciencias Sociales', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (11, 'Clubes', 4,'Clubes Bachillerato', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (12, 'Ajedréz', 10,'Dimensión Cognitiva', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (13, 'Ciencias', 18,'Dimensión Cognitiva', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (14, 'Democracia', 14,'Dimensión Cognitiva', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (15, 'Escritura', 6,'Dimensión Cognitiva', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (16, 'Matemáticas', 17,'Dimensión Cognitiva', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (17, 'Desarrollo del Lenguaje', 6,'Dimensión Comunicativa', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (18, 'Español', 11,'Dimensión Comunicativa', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (19, 'Inglés', 15,'Dimensión Comunicativa', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (20, 'Estimulación Sensoriomotriz', 6,'Dimensión Corporal', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (21, 'Expresión Corporal', 10,'Dimensión Corporal ', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (22, 'Educación física', 10,'Dimensión Corporal ', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (23, 'Arte', 13,'Dimensión Estética', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (24, 'Música', 12,'Dimensión Estética', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (25, 'Educación Religiosa Escolar', 9,'Dimensión Etica Actitudes y Valores', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (26, 'Educación Sexual', 24,'Dimensión Etica Actitudes y Valores', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (27, 'Valores', 24,'Dimensión Etica Actitudes y Valores', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (28, 'Biblioteca', 6,'Dimensión Socio-afectiva', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (29, 'Sistemas', 3,'Dimensión Tecnológica', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (30, 'Conducta', 8,'Disciplinario', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (31, 'Disciplina', 8,'Disciplinario', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (32, 'Solidaridad', 8,'Disciplinario', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (33, 'Música', 12,'Educación Artistica', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (34, 'Teclado', 12,'Educación Artistica', 33)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (35, 'Cuerdas', 12,'Educación Artistica', 33)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (36, 'Violin', 12,'Educación Artistica', 33)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (37, 'Vientos', 12,'Educación Artistica', 33)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (38, 'Teclado', 12,'Educación Artística', 33)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (39, 'Arte', 12,'Educación Artística', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (40, 'Arte Bidimensional', 13,'Educación Artística', 40)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (41, 'Arte Tridimensional', 13,'Educación Artística', 40)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (42, 'Educación Sexual', 24,'Educación Etica y en valores Humanos', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (43, 'Etica y Valores', 24,'Educación Etica y en valores Humanos', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (44, 'Terapia Ocupacional', 6,'Educación Etica y en valores Humanos', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (45, 'Educación Física', 10,'Educación Física', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (46, 'Categorización del Movimiento Locomoción', 10,'Educación Física', 48)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (47, 'Categorización del Movimiento Manipulación', 10,'Educación Física', 48)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (48, 'Cualidades Físicas', 10,'Educación Física', 48)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (49, 'Esquema Corporal', 10,'Educación Física', 48)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (50, 'Capacidades Físicas', 10,'Educación Física, Recreación y Deportes', 48)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (51, 'Condición', 10,'Educación Física, Recreación y Deportes', 51)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (52, 'Coordinación', 10,'Educación Física, Recreación y Deportes', 51)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (53, 'Categoria de Movimiento', 10,'Educación Física, Recreación y Deportes', 48)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (54, 'Básicas', 10,'Educación Física, Recreación y Deportes', 49)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (55, 'Coordinativas', 10,'Educación Física, Recreación y Deportes', 49)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (56, 'Esquema Corporal', 10,'Educación Física, Recreación y Deportes', 48)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (57, 'Grupo Atlético', 10,'Educación Física, Recreación y Deportes', 48)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (58, 'Religión', 9,'Educación Religiosa Escolar', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (59, 'Filosofía', 14,'Filosofía', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (60, 'Español', 11,'Humanidades ', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (61, 'Francés', 23,'Humanidades ', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (62, 'Inglés', 15,'Humanidades ', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (63, 'Algebra', 17,'Matemáticas', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (64, 'Aritmética y Geometría', 17,'Matemáticas', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (65, 'Cálculo', 17,'Matemáticas', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (66, 'Matemáticas', 17,'Matemáticas', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (67, 'Trigonometría y Estadística', 17,'Matemáticas', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (68, 'Música', 12,'Música', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (69, 'Desarrollo Manual', 6,'Procesos', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (70, 'Ensayo', 7,'Procesos', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (71, 'Desarrollo del Pensamiento', 8,'Procesos', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (72, 'Sistemas', 3,'Tecnología e Informática', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (73, 'Ritmo', 12,'Dimensión Estética', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (74, 'Lectura y Escritura', 11,'Dimensión Comunicativa', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (75, 'Casas', 2,'Casas', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (76, 'Orientación Profesional', 24,'Educación Etica y en valores Humanos', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (77, 'Dirección de Grupo', 2,'Dirección de Grupo', NULL)
INSERT INTO Materia (Id, Nombre, IdDepartamentoAcademico, Area, Padre) VALUES (78, 'Escuelas', 6,'Educación Física', NULL)
SET IDENTITY_INSERT Materia OFF